[package]
name = "crosspub"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tinytemplate = "1.2.1"
toml = "0.5"
xdg = "2.4"
