[site]
# The name of your site which gets used in tab titles and the header.
name = "hiroantag's web living room"
# The base url of yor site.
url = "retrace.club/"
# Your tilde extension (without the ~ character)
username = "hiroantag"
html_root = "/home/hiroantag/public_html"
gemini_root = "/home/hiroantag/public_gemini"
posts_subdir = "posts"
topics_subdir = "topics"

[homepage]
# When custom_homepage = true crosspub generates index.html and index.gmi
custom_homepage = false
# If list_posts_on_homepage = true then crosspub generates a list of links on
# index.html and index.gmi.
#
# If false then crosspub will generate a list of links in posts_subdir/index.html
# and put a link to that page on the homepage.
list_posts_on_homepage = true
use_about_page = false
about_path = "/path/to/about.gmi"
