# The name of your site which gets used in tab titles and the header.
site_name = "example"

# The full url of yor site.
site_url = "http://example.com/"

# Set this to true if you want crosspub to generate index.html for you. The
# generated index.html includes the site title, an about message, and a list of
# posts.
default_index = false;
# Change this to the path of a gemtext file that will be used to generate
# index.html. Only used if default_index = true.
about = "/path/to/about.gmi"
# Set these to HTML files containing a header and footer respectively.
# The header is NOT a <header> but rather the elements that should remain
# consistent between pages.
header = "/path/to/header.html"
footer = "/path/to/footer.html"
# Set this to true if you want to load custom CSS, otherwise the default style
# will be used.
default_style = false;
# Change this to a path to your custom CSS. Only used if default_style = false.
# This path is RELATIVE to your html_root.
css = "path/to/style.css"

# Root directories of html and gemini sites. Change these to the actual paths.
html_root = "/home/user/public_html"
gemini_root = "/home/user/public_gemini"
# The name of the directory containing posts in both html_root and gemini_root.
# If it doesn't already exist it will be created.
post_dir = "posts"
