# The name of your site which gets used in tab titles and the header.
name = "example"
# The full url of yor site.
url = "http://example.com/"
# Your tilde extension (without the ~ character)
username = "user"

# Set this to true if you want crosspub to generate index.html for you.
#
# If default_index = true: post list is generated on the user's
# homepage.
#
# If default_index = false: the user provides their own homepage and the post
# list is generated at /posts/posts.html
default_index = true;
# Change this to the path of a gemtext file that will be used to generate
# about.html. Only used if default_index = true.
about = "/path/to/about.gmi"
# Change this to the path to your HTML post template file
html_template = "/path/to/template.html"
# Change this to the path to your gemini post template file
gemini_template = "/path/to/template.gmi"

# Root directories of html and gemini sites. Change these to the actual paths.
html_root = "/home/user/public_html"
gemini_root = "/home/user/public_gemini"

# Set this to true if you want to load custom CSS, otherwise the default style
# will be used.
default_style = false;
# Change this to a path to your custom CSS. Only used if default_style = false.
# This path is RELATIVE to your html_root.
css = "path/to/style.css"
