[site]
# The name of your site which gets used in tab titles and the header.
name = "Example Site"

# The base url of yor site.
url = "example.com/"

# Your tilde extension (without the ~ character)
username = "user"

# The directories containing your HTML and Gemini roots
html_root = "/home/user/public_html"
gemini_root = "/home/user/public_gemini"

[homepage]
# If true crosspub will look in ~/.local/share/crosspub (or whatever your
# XDG_DATA_HOME is set as) to find an about.gmi.
use_about_page = false

# When this is true crosspub generates a posts.html file in your posts_subdir
# with links to all your posts.
post_list = false
