[site]
# The name of your site which gets used in tab titles and the header.
name = "hiroantag's web living room"

# The base url of yor site.
url = "retrace.club/"

# Your tilde extension (without the ~ character)
username = "hiroantag"

# The directories containing your HTML and Gemini roots
html_root = "/home/hiroantag/public_html"
gemini_root = "/home/hiroantag/public_gemini"

[homepage]
# If true crosspub will look in ~/.local/share/crosspub (or whatever your
# XDG_DATA_HOME is set as) to find an about.gmi.
use_about_page = false

# When this is true crosspub generates a posts.html file in your posts_subdir
# with links to all your posts.
post_list = false
